// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NotificationInterface is an autogenerated mock type for the NotificationInterface type
type NotificationInterface struct {
	mock.Mock
}

// SendNotifications provides a mock function with given fields: tokens, userID, message
func (_m *NotificationInterface) SendNotifications(tokens string, userID string, message string) error {
	ret := _m.Called(tokens, userID, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(tokens, userID, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationInterface creates a new instance of NotificationInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationInterface {
	mock := &NotificationInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
