// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ValidationInterface is an autogenerated mock type for the ValidationInterface type
type ValidationInterface struct {
	mock.Mock
}

// ValidateRequest provides a mock function with given fields: request
func (_m *ValidationInterface) ValidateRequest(request interface{}) []string {
	ret := _m.Called(request)

	var r0 []string
	if rf, ok := ret.Get(0).(func(interface{}) []string); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NewValidationInterface creates a new instance of ValidationInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidationInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidationInterface {
	mock := &ValidationInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
