// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	fundraise "raihpeduli/features/fundraise"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// DeleteByID provides a mock function with given fields: fundraiseID
func (_m *Repository) DeleteByID(fundraiseID int) (int, error) {
	ret := _m.Called(fundraiseID)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int, error)); ok {
		return rf(fundraiseID)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(fundraiseID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(fundraiseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: newFundraise
func (_m *Repository) Insert(newFundraise fundraise.Fundraise) (int, error) {
	ret := _m.Called(newFundraise)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(fundraise.Fundraise) (int, error)); ok {
		return rf(newFundraise)
	}
	if rf, ok := ret.Get(0).(func(fundraise.Fundraise) int); ok {
		r0 = rf(newFundraise)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(fundraise.Fundraise) error); ok {
		r1 = rf(newFundraise)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Paginate provides a mock function with given fields: page, size, title
func (_m *Repository) Paginate(page int, size int, title string) ([]fundraise.Fundraise, error) {
	ret := _m.Called(page, size, title)

	var r0 []fundraise.Fundraise
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]fundraise.Fundraise, error)); ok {
		return rf(page, size, title)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []fundraise.Fundraise); ok {
		r0 = rf(page, size, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fundraise.Fundraise)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) error); ok {
		r1 = rf(page, size, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectByID provides a mock function with given fields: fundraiseID
func (_m *Repository) SelectByID(fundraiseID int) (*fundraise.Fundraise, error) {
	ret := _m.Called(fundraiseID)

	var r0 *fundraise.Fundraise
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*fundraise.Fundraise, error)); ok {
		return rf(fundraiseID)
	}
	if rf, ok := ret.Get(0).(func(int) *fundraise.Fundraise); ok {
		r0 = rf(fundraiseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fundraise.Fundraise)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(fundraiseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *Repository) Update(_a0 fundraise.Fundraise) (int, error) {
	ret := _m.Called(_a0)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(fundraise.Fundraise) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(fundraise.Fundraise) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(fundraise.Fundraise) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadFile provides a mock function with given fields: file, objectName
func (_m *Repository) UploadFile(file multipart.File, objectName string) (string, error) {
	ret := _m.Called(file, objectName)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(multipart.File, string) (string, error)); ok {
		return rf(file, objectName)
	}
	if rf, ok := ret.Get(0).(func(multipart.File, string) string); ok {
		r0 = rf(file, objectName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(multipart.File, string) error); ok {
		r1 = rf(file, objectName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
