// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	auth "raihpeduli/features/auth"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// InsertVerification provides a mock function with given fields: email, verificationKey
func (_m *Repository) InsertVerification(email string, verificationKey string) error {
	ret := _m.Called(email, verificationKey)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, verificationKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: email
func (_m *Repository) Login(email string) (*auth.User, error) {
	ret := _m.Called(email)

	var r0 *auth.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: newUser
func (_m *Repository) Register(newUser *auth.User) (*auth.User, error) {
	ret := _m.Called(newUser)

	var r0 *auth.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*auth.User) (*auth.User, error)); ok {
		return rf(newUser)
	}
	if rf, ok := ret.Get(0).(func(*auth.User) *auth.User); ok {
		r0 = rf(newUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*auth.User) error); ok {
		r1 = rf(newUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectByEmail provides a mock function with given fields: email
func (_m *Repository) SelectByEmail(email string) (*auth.User, error) {
	ret := _m.Called(email)

	var r0 *auth.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendOTPByEmail provides a mock function with given fields: email, otp
func (_m *Repository) SendOTPByEmail(email string, otp string) error {
	ret := _m.Called(email, otp)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
